export const GET_PLAYERS_SUCCESS = 'GET_PLAYERS_SUCCESS'
export const ADD_PLAYER_SUCCESS = 'ADD_PLAYER_SUCCESS'
export const DELETE_PLAYER_SUCCESS = 'DELETE_PLAYER_SUCCESS'

export const SET_MODAL_SUCCESS = 'SET_MODAL_SUCCESS'
export const TOGGLE_MODAL_SUCCESS = 'TOGGLE_MODAL_SUCCESS'
