// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/56295f5058cac7ae458540423c50ac2dcf9fc711/lolex/lolex.d.ts
declare module 'lolex' {
	export interface Clock {
		setTimeout(callback: () => any, timeout: number): number;
		setInterval(callback: () => any, timeout: number): number;
		setImmediate(callback: () => any): number;

		clearTimeout(id: number): void;
		clearInterval(id: number): void;
		clearImmediate(id: number): void;

		tick(ms: number): void;
		uninstall(): void;
	}

	export function createClock(now?: number): Clock;

	export function install(now?: number, toFake?: string[]): Clock;
	export function install(context?: any, now?: number, toFake?: string[]): Clock;
}
