// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/9038485f53df7d3241fac74562aacfcee42b8857/webpack-merge/webpack-merge.d.ts
declare module "webpack-merge" {
    import {Configuration} from "webpack";

    interface WebpackMerge {
        /**
         * Merge multiple webpack configurations into one.
         */
        (...configs: Configuration[]): Configuration;

        /**
         * Merge multiple webpack configurations into one, with smart merging of loaders.
         */
        smart(...configs: Configuration[]): Configuration;
    }

    const merge: WebpackMerge;
    export = merge;
}
